[target.'cfg(target_os = "windows")']
rustflags = [
"-C", "target-cpu=haswell",
"--cfg", "windows_slim_errors",
]
[target.'cfg(target_os = "linux")']
rustflags = [
"-C", "target-cpu=haswell"
]

[profile.release]
codegen-units = 1
debug = false
lto = true
opt-level = 's'
panic = "abort"
strip = true
